stages:
  - build_and_test
  - push_to_dockerhub
  - deploy_on_EC2


build_job:
  stage: build_and_test
  script: 
    - docker build -t notes-app:latest .
    - echo "Building notes-app image....."
  tags:
    - dev
  artifacts:
    paths:
      -  builds/
    expire_in: 1 day


push_job:
  stage: push_to_dockerhub
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PAT 
    - docker image tag notes-app:latest $DOCKERHUB_USER/notes-app:latest
    - docker push $DOCKERHUB_USER/notes-app:latest
    - echo "Pushing image to dockerhub....."
  tags:
    - dev
  artifacts:
    paths:
      -  builds/
    expire_in: 1 day

deploy_job:
  stage: deploy_on_EC2
  script: 
    - docker compose up -d
    - echo "Starting containers....."
  tags:
    - dev
  artifacts:
    paths:
      -  builds/
    expire_in: 1 day
